package eu.kanade.tachiyomi.extension.en.tailspace

// Fallback list generated from the supplied Tailspace HTML and HAR captures.
// scripts/update_tags.py refreshes this list from all browse pages before each build.
internal data class TailspaceTag(val name: String, val id: Int)

internal val TAILSPACE_TAGS = listOf(
    TailspaceTag("absol", 1),
    TailspaceTag("age difference", 2),
    TailspaceTag("ampharos", 827),
    TailspaceTag("anal", 5),
    TailspaceTag("andromorph", 875),
    TailspaceTag("anon-kun", 7),
    TailspaceTag("anthro", 8),
    TailspaceTag("arcanine", 12),
    TailspaceTag("autofellatio", 15),
    TailspaceTag("avian", 16),
    TailspaceTag("badger", 17),
    TailspaceTag("bat", 19),
    TailspaceTag("bdsm", 20),
    TailspaceTag("bear", 21),
    TailspaceTag("belly bulge", 22),
    TailspaceTag("big ass", 23),
    TailspaceTag("big balls", 24),
    TailspaceTag("big boobs", 25),
    TailspaceTag("big penis", 27),
    TailspaceTag("bird", 28),
    TailspaceTag("biting", 29),
    TailspaceTag("blaziken", 30),
    TailspaceTag("blindfolded", 836),
    TailspaceTag("blood", 31),
    TailspaceTag("blowjob", 32),
    TailspaceTag("bondage", 308),
    TailspaceTag("boobjob", 933),
    TailspaceTag("bovine", 33),
    TailspaceTag("braixen", 36),
    TailspaceTag("buizel", 38),
    TailspaceTag("bukkake", 39),
    TailspaceTag("canine", 42),
    TailspaceTag("canine penis", 43),
    TailspaceTag("casual nudity", 808),
    TailspaceTag("cat", 44),
    TailspaceTag("caught", 45),
    TailspaceTag("charizard", 46),
    TailspaceTag("chipmunk", 52),
    TailspaceTag("chubby", 865),
    TailspaceTag("condom", 831),
    TailspaceTag("cow", 55),
    TailspaceTag("creampie", 56),
    TailspaceTag("creampie eating", 872),
    TailspaceTag("crossdressing", 57),
    TailspaceTag("cum in ass", 800),
    TailspaceTag("cum in mouth", 60),
    TailspaceTag("cum inside", 799),
    TailspaceTag("cum on face", 803),
    TailspaceTag("cumflation", 61),
    TailspaceTag("cumshot", 62),
    TailspaceTag("cunnilingus", 63),
    TailspaceTag("cute", 65),
    TailspaceTag("deepthroat", 856),
    TailspaceTag("deer", 66),
    TailspaceTag("demon", 68),
    TailspaceTag("dick on dick", 71),
    TailspaceTag("digimon", 72),
    TailspaceTag("dinosaur", 73),
    TailspaceTag("dog", 75),
    TailspaceTag("double penetration", 77),
    TailspaceTag("double penis", 818),
    TailspaceTag("dragon", 79),
    TailspaceTag("eevee", 82),
    TailspaceTag("eggs", 83),
    TailspaceTag("emotional", 87),
    TailspaceTag("equine", 88),
    TailspaceTag("espeon", 89),
    TailspaceTag("excessive cum", 802),
    TailspaceTag("facesitting", 90),
    TailspaceTag("fat", 92),
    TailspaceTag("feet", 93),
    TailspaceTag("feline", 94),
    TailspaceTag("femboy", 95),
    TailspaceTag("femdom", 96),
    TailspaceTag("fennec", 97),
    TailspaceTag("feral", 99),
    TailspaceTag("feral penis", 100),
    TailspaceTag("feral vagina", 101),
    TailspaceTag("feraligatr", 102),
    TailspaceTag("fetish", 894),
    TailspaceTag("fingering", 104),
    TailspaceTag("fisting", 106),
    TailspaceTag("flamedramon", 108),
    TailspaceTag("flareon", 109),
    TailspaceTag("footjob", 113),
    TailspaceTag("foreskin", 798),
    TailspaceTag("fox", 114),
    TailspaceTag("frotting", 117),
    TailspaceTag("gaping", 837),
    TailspaceTag("garchomp", 119),
    TailspaceTag("glaceon", 126),
    TailspaceTag("goat", 127),
    TailspaceTag("goodra", 330),
    TailspaceTag("griffin", 131),
    TailspaceTag("group", 132),
    TailspaceTag("group sex", 893),
    TailspaceTag("grovyle", 133),
    TailspaceTag("growth", 902),
    TailspaceTag("gym", 840),
    TailspaceTag("handjob", 135),
    TailspaceTag("hands free", 857),
    TailspaceTag("helluva boss", 967),
    TailspaceTag("horse", 137),
    TailspaceTag("horsecock", 138),
    TailspaceTag("human", 140),
    TailspaceTag("humiliation", 141),
    TailspaceTag("husky", 881),
    TailspaceTag("hyper", 144),
    TailspaceTag("hypnosis", 145),
    TailspaceTag("impregnation", 806),
    TailspaceTag("in heat", 147),
    TailspaceTag("in public", 148),
    TailspaceTag("incest", 149),
    TailspaceTag("incineroar", 313),
    TailspaceTag("inflation", 150),
    TailspaceTag("intersex", 927),
    TailspaceTag("jackal", 152),
    TailspaceTag("jolteon", 153),
    TailspaceTag("kissing", 159),
    TailspaceTag("knotting", 160),
    TailspaceTag("kommo-o", 162),
    TailspaceTag("leafeon", 164),
    TailspaceTag("leopard", 168),
    TailspaceTag("licking", 169),
    TailspaceTag("lion", 170),
    TailspaceTag("litten", 318),
    TailspaceTag("locker room", 839),
    TailspaceTag("long story", 172),
    TailspaceTag("loona", 833),
    TailspaceTag("lopunny", 173),
    TailspaceTag("lucario", 174),
    TailspaceTag("lugia", 175),
    TailspaceTag("lycanroc", 177),
    TailspaceTag("lynx", 178),
    TailspaceTag("macro", 871),
    TailspaceTag("magic", 179),
    TailspaceTag("maid", 312),
    TailspaceTag("mammal", 947),
    TailspaceTag("masturbation", 180),
    TailspaceTag("milk", 309),
    TailspaceTag("muscular", 185),
    TailspaceTag("my little pony", 941),
    TailspaceTag("non-anthro", 834),
    TailspaceTag("oral", 315),
    TailspaceTag("orgy", 844),
    TailspaceTag("otter", 194),
    TailspaceTag("outside", 195),
    TailspaceTag("palworld", 937),
    TailspaceTag("pawjob", 971),
    TailspaceTag("photography", 202),
    TailspaceTag("pikachu", 204),
    TailspaceTag("pokemon", 940),
    TailspaceTag("pony", 208),
    TailspaceTag("presenting", 333),
    TailspaceTag("public indecency", 900),
    TailspaceTag("public sex", 905),
    TailspaceTag("rabbit", 213),
    TailspaceTag("raccoon", 214),
    TailspaceTag("rapidash", 852),
    TailspaceTag("raptor", 218),
    TailspaceTag("rattata", 222),
    TailspaceTag("riding", 915),
    TailspaceTag("rimming", 229),
    TailspaceTag("robot", 231),
    TailspaceTag("romantic", 234),
    TailspaceTag("saliva", 237),
    TailspaceTag("scalie", 240),
    TailspaceTag("sceptile", 241),
    TailspaceTag("sex change", 246),
    TailspaceTag("sex toy", 247),
    TailspaceTag("shark", 248),
    TailspaceTag("sheath play", 801),
    TailspaceTag("siblings", 877),
    TailspaceTag("size difference", 252),
    TailspaceTag("skunk", 253),
    TailspaceTag("sleeping", 331),
    TailspaceTag("slit", 307),
    TailspaceTag("small boobs", 860),
    TailspaceTag("snake", 256),
    TailspaceTag("sneasel", 257),
    TailspaceTag("sniffing", 842),
    TailspaceTag("spanking", 260),
    TailspaceTag("spyro", 306),
    TailspaceTag("story", 263),
    TailspaceTag("surprise gay", 264),
    TailspaceTag("surprise sex", 928),
    TailspaceTag("sweaty", 265),
    TailspaceTag("sylveon", 267),
    TailspaceTag("tailfucking", 268),
    TailspaceTag("tentacles", 270),
    TailspaceTag("threesome", 832),
    TailspaceTag("tiger", 275),
    TailspaceTag("titjob", 276),
    TailspaceTag("torture", 849),
    TailspaceTag("trans", 858),
    TailspaceTag("transformation", 278),
    TailspaceTag("treecko", 279),
    TailspaceTag("twilight sparkle", 283),
    TailspaceTag("twink", 843),
    TailspaceTag("typhlosion", 316),
    TailspaceTag("umbreon", 285),
    TailspaceTag("underwear", 841),
    TailspaceTag("unwilling", 288),
    TailspaceTag("vaginal", 289),
    TailspaceTag("vaporeon", 290),
    TailspaceTag("violence", 291),
    TailspaceTag("vore", 292),
    TailspaceTag("vulpix", 293),
    TailspaceTag("watersports", 294),
    TailspaceTag("weavile", 295),
    TailspaceTag("wolf", 297),
    TailspaceTag("workplace sex", 907),
    TailspaceTag("yveltal", 299),
    TailspaceTag("zoroark", 303),
    TailspaceTag("zorua", 304),
    TailspaceTag("zygarde", 925),
)
